server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/pai?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: shiyiran
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mapper/*.xml
debug: false
logging:
  file:
    path: D:/ketangpai-dev.log

