server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://155.32.0.12:3306/pai?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: shiyiran
  thymeleaf:
    cache: true
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  mapper-locations: classpath:mapper/*.xml
debug: false
logging:
  file:
    path: /local/user/ketangpai-prd.log