server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ketangpai?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    data-username: root
    data-password: shiyiran
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  mapper-locations: classpath:mapper/*.xml
debug: false
logging:
  file:
    path: D:/ketangpai-dev.log